version: "3.9"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    ports:
      - "8080:8080"
    command: >
      java -cp app.jar com.mango.App
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    container_name: product-benchmark
    depends_on:
      - app
    command: sh -c "chmod +x /app/benchmark.sh && /app/benchmark.sh"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M